name: flutter_face_sdk
description: A new Flutter FFI plugin project.
version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera: ^0.11.2
  path_provider: ^2.0.2

dev_dependencies:
  # ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # Please refer to README.md for a detailed explanation.
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true

  assets:
    - data/detection/ssd/ssd_new.conf
    - data/detection/ssd/ssd_f8.conf
    - data/internal/13db040b9a9b1f5e84218454df3a11d2627758e64df3de5a51e57afce4c01872
    - data/internal/7b58eb1179ad97844e9705490830a97b61b83f8017b71a40733ba46c8da22420
    - data/internal/caa80ea64c13d61bc6c341756abd3eb9b0aa0e252354b6cd1013018c73a03218
    - data/internal/3692cda6cb9d19920044b5483337d9c20a92c4f92c5ea912ef87bffa897b79bc
    - data/internal/7c3343b6ec7e331ac787501f9b3090a05b2d938e4ae1de59a121b87797803586
    - data/internal/e5082d08f9c9486c186b740ef927f240bb5a498b3fde95a2f653aea21061f768
    - data/internal/4235ac64f80d599ab219df183829af13e12a8c9b96d0eaf41988a83b9693592a
    - data/internal/a4e42fe3ea6209e316056bc41cbe40a39c7159b2655756f08d100ff9883ed9ff
    - data/internal/e911c1a0adf6bf47951b12e9c7ff48f38775f8d5d958dfc2d9018095b05c4035
    - data/internal/51adfd9d6c77f4c7c439302292d6dcac30a5aea1f1816c6a2079d41bc1b8e747
    - data/internal/aa6e956ba20a6190610da3dc3dc7e5bb4fb650cdfb467e56763883473d0df2c7
    - data/internal/f21beb39325745062bcb0e2ea076f6413be89025a42d1ab1e1307183ddbe1a51
    - data/internal/5ba89ae7a268036d96fae6de51d921f16aa11de643ffc95096ed0670bc55da88
    - data/internal/ac3a38c3777a22e08c35cffaef9200ba51d89eb118966834a6603166c76010d1
    - data/internal/f66284f5b1e14853d4aefecc549839145656388e4482855bc5de5d92752a8858
    - data/internal/7484fdb5bb69d3283c8aacd885ee50d8ce53f21c7bbfc33509185fe239f2ad41
    - data/internal/b333d4da1a385777d90cb4d335383cb28b10d5319f6a8417d963ed01b5abacdb
    - data/pipelines/pegasus.json
    - data/preprocessing/face_params.conf
    - data/quality/exposition.conf
   
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
